version: "3"
services:
  pihole1:
    image: pihole/pihole:latest
    restart: unless-stopped
    #network_mode: "host"
    cap_add:
        - NET_ADMIN
    environment:
      ServerIP: 10.0.0.15
      WEBPASSWORD: athena1dog
      #DNS1: 1.1.1.1
      #DNS2: 1.0.0.1
      VIRTUAL_HOST: pi.hole
      DNSMASQ_LISTENING: all
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - '/opt/pyhole/docker/pihole/pihole/:/etc/pihole/'
      - '/opt/pyhole/docker/pihole/dnsmasq.d/:/etc/dnsmasq.d/'